// ==UserScript==
// @name         DB Monkey
// @namespace    https://db.datarecovery.com
// @version      0.1
// @description  DB quality of life improvements!
// @author       Alex Sweet
// @match           https://db.datarecovery.com/*
// @require         http://code.jquery.com/jquery-latest.js
// @require         https://raw.githubusercontent.com/sweetgiorni/dbmonkey/master/dbmonkey.js

// @grant GM_setValue
// @grant GM_getValue
// @grant GM_deleteValue

// ==/UserScript==
